planner_configs:
  SBLkConfigDefault:
    type: geometric::SBL
  LBKPIECEkConfigDefault:
    type: geometric::LBKPIECE
  RRTkConfigDefault:
    type: geometric::RRT
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
  LazyRRTkConfigDefault:
    type: geometric::LazyRRT
  ESTkConfigDefault:
    type: geometric::EST
  KPIECEkConfigDefault:
    type: geometric::KPIECE
  RRTStarkConfigDefault:
    type: geometric::RRTstar
  BKPIECEkConfigDefault:
    type: geometric::BKPIECE
  SemiPersistentLazyPRMstar:
    type: geometric::LazyPRMstar
    multi_query_planning_enabled: true
    store_planner_data: false
    load_planner_data: false
    optimization_objective: MechanicalWorkOptimizationObjective
  SemiPersistentLazyPRM:
    type: geometric::LazyPRM
    multi_query_planning_enabled: true
    store_planner_data: false
    load_planner_data: false
    optimization_objective: MechanicalWorkOptimizationObjective
  RRTConnectkConfigMechanical:
    type: geometric::RRTConnect
    optimization_objective: MechanicalWorkOptimizationObjective
  RRTStarkConfigMechanical:
    type: geometric::RRTstar
    optimization_objective: MechanicalWorkOptimizationObjective
  RRTStarkConfigState:
    type: geometric::RRTstar
    optimization_objective: StateCostIntegralObjective
  
left_arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - SemiPersistentLazyPRMstar
    - SemiPersistentLazyPRM
    - RRTConnectkConfigMechanical
    - RRTStarkConfigMechanical
    - RRTStarkConfigState
  projection_evaluator: joints(left_s0,left_s1)
  longest_valid_segment_fraction: 0.05
right_arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - SemiPersistentLazyPRMstar
    - SemiPersistentLazyPRM
    - RRTConnectkConfigMechanical
    - RRTStarkConfigMechanical
    - RRTStarkConfigState
  projection_evaluator: joints(right_s0,right_s1)
  longest_valid_segment_fraction: 0.05
both_arms:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
    - RRTStarkConfigMechanical
    - RRTStarkConfigState
  projection_evaluator: joints(right_s0,right_s1, left_s0, left_s1)
  longest_valid_segment_fraction: 0.05
left_hand:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
right_hand:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - SBLkConfigDefault
    - LBKPIECEkConfigDefault
    - RRTkConfigDefault
    - RRTConnectkConfigDefault
    - ESTkConfigDefault
    - KPIECEkConfigDefault
    - BKPIECEkConfigDefault
    - RRTStarkConfigDefault
